config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to @kitten, notice: 'Kitten was successfully created. Oh how cute!' }
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { render :new }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end    
  end

  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to @kitten, notice: 'Kitten was successfully updated. Awwww that is so precious' }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end    
  end

  def edit
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end    
  end

  def destroy
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to kittens_url, notice: 'Kitten was successfully destroyed. You are a horrible person!' }
      format.json { head :no_content }
    end    
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: @kitten.name, autofocus: true %>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <%= f.label :cuteness, "Cuteness Rating (1 to 10)" %>
  <%= f.text_field :cuteness %>
  <%= f.label :softness, "Softness Rating (1 to 10)" %>
  <%= f.text_field :softness %>
  <%= f.submit 'Kittenize' %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit <%= @kitten.name %></h1>
<%= render 'form' %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= link_to 'Show', kitten %></td>
        <td><%= link_to 'Edit', edit_kitten_path(kitten) %></td>
        <td><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure you want to kill a cute kitten?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1>Kitten Details</h1>
<p><strong>Kitten Name: </strong><%= @kitten.name %></p>
<p><strong>Kitten Age: </strong><%= @kitten.age %></p>
<p><strong>Kitten Cuteness: </strong><%= @kitten.cuteness %></p>
<p><strong>Kitten Softness: </strong><%= @kitten.softness %></p>

<%= link_to 'Edit this Kitten', edit_kitten_path(@kitten) %> |
<%= link_to 'Back to Kitten List', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{type}" %>
    <% end %> 
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <p>What the heck, nucklehead!</p>
      <p>The form contains <%= pluralize(object.errors.count, "error") %>.</p>
    </div>
    <ul>
      <p>Fix this stuff, bonehead</p>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>